@ECHO OFF
TITLE MAPING NETWORK DRIVES.
 
SET DBSERVER=INTEGRASQL
 
SET INTAPPLTR=S:
SET INTAPPSHARE=Integra
SET INTUSERLTR=T:
SET INTUSERSHARE=int_Users$
 
:MKINTUSERDIR
if exist \\%DBSERVER%\%INTUSERSHARE%\%USERNAME% goto DISCONNECT
mkdir \\%DBSERVER%\%INTUSERSHARE%\%USERNAME%
mkdir \\%DBSERVER%\%INTUSERSHARE%\%USERNAME%\Environment\
mkdir \\%DBSERVER%\%INTUSERSHARE%\%USERNAME%\Reports
 
 
:DISCONNECT
if exist %INTAPPLTR% net use %INTAPPLTR% /delete /y
if exist %INTUSERLTR% net use %INTUSERLTR% /delete /y
 
:MAPDRIVES
if not exist %INTAPPLTR% net use %INTAPPLTR% \\%DBSERVER%\%INTAPPSHARE% /y
if not exist %INTUSERLTR% net use %INTUSERLTR% \\%DBSERVER%\%INTUSERSHARE%\%USERNAME% /y
